services:
  cassandra:
    image: cassandra:4
    container_name: cassandra
    restart: always
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=256M
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status | grep -q 'UN'" ]
      interval: 15s
      timeout: 5s
      retries: 10
    networks:
      - crypto-network
  cassandra-init:
    image: cassandra:latest
    container_name: cassandra-init
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./api/scripts/schema_cassandra.cql:/init.cql
    entrypoint: >
      bash -c "echo 'Cassandra prête, initialisation du schéma...'; cqlsh cassandra 9042 -f /init.cql && echo 'Schéma initialisé avec succès.'"
    networks:
      - crypto-network
