include:
  - docker-compose.airflow.yml
  - docker-compose.cassandra.yml
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./data:/app/data
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - PYTHONPATH=/app:/app/src
    depends_on:
      cassandra-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    networks:
      airflow-network: {}
      crypto-network: {}
      monitoring-network:
        aliases:
          - api-monitoring
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/docs')" ]
      interval: 10s
      timeout: 5s
      retries: 6
  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/scripts/schema_postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - crypto-network
  tests:
    image: python:3.11-slim
    container_name: tests
    profiles:
      - test
    volumes:
      - ./tests:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    depends_on:
      api:
        condition: service_healthy
    entrypoint: >
      sh -c " pip install httpx && pip install pytest && pytest -v -s"
    networks:
      crypto-network:
  streamlit:
    build: ./streamlit
    command: streamlit run streamlit/main.py --server.port 8501
    volumes:
      - ./:/usr/src/app
    ports:
      - 8501:8501
    image: yourstreamlitapp:latest
    depends_on:
      api:
        condition: service_healthy
    networks:
      crypto-network:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-network
    depends_on:
      api:
        condition: service_healthy
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    logging:
      driver: "none"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - monitoring-network
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    logging:
      driver: "none"
    networks:
      - monitoring-network

  promtail:
    image: grafana/promtail:3.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail/config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - monitoring-network
    depends_on:
      - loki
  adminer:
    image: adminer:latest
    container_name: projet_test_adminer
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - crypto-network

volumes:
  postgres_data:
  cassandra_data:
networks:
  airflow-network:
  crypto-network:
  monitoring-network:
