{
 "title": "Logs des Services Docker",
 "tags": [
  "logs",
  "docker"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Logs - Service FastAPI",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=~\".*api.*\"}"
    }
   ]
  },
  {
   "title": "Logs - Service PostgreSQL",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=~\".*postgres.*\"}"
    }
   ]
  },
  {
   "title": "Logs - Service Airflow",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=~\".*airflow-worker.*\"}"
    }
   ]
  },
  {
   "title": "Logs - Service Cassandra",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=~\".*cassandra.*\"}"
    }
   ]
  }
 ]
}